import { ClientSession, Types } from "mongoose";
import AppError from "../../errors/handleAppError.js";
import { AcademicSemesterModel } from "../academicSemester/academicSemester.model.js";
import { CounterService } from "../counter/counter.service.js";

//set id automatically generated by mongoose, we can also set it manually if needed, but it's generally recommended to let mongoose handle the generation of unique IDs for documents in the database to ensure consistency and avoid potential conflicts or errors that may arise from manually setting IDs.
const generatedStudentId = async (
  admissionSemesterId: string,
  session?: ClientSession,
): Promise<string> => {
  const normalizedSemesterId = admissionSemesterId?.trim();

  if (!normalizedSemesterId || !Types.ObjectId.isValid(normalizedSemesterId)) {
    throw new AppError("Invalid admission semester id", 400);
  }

  // First, we need to retrieve the academic semester data based on the provided admissionSemesterId to get the necessary information for generating the student ID, such as the admission year and semester code, which will be used to create a unique identifier for the student.
  const semesterData = await AcademicSemesterModel.findOne({
    _id: normalizedSemesterId,
    isDeleted: false,
  }).session(session ?? null);
  if (!semesterData) {
    throw new AppError("Admission semester not found", 404);
  }
  const yearValue =
    semesterData.year instanceof Date
      ? semesterData.year.getFullYear().toString()
      : new Date(semesterData.year).getFullYear().toString();

  if (!yearValue || yearValue === "NaN") {
    throw new AppError("Invalid semester year", 500);
  }

  const counterId = `${yearValue}${semesterData.code}`; // Generate a unique counter ID based on the admission year and semester code, this will help to create a unique identifier for each student that incorporates information about their admission semester, which can be useful for organizing and categorizing student records in the database based on their admission semesters.
  // Next, we need to interact with the CounterService to create or find a counter document in the database that corresponds to the generated counter ID, this will allow us to keep track of the sequence of student IDs for each admission semester and ensure that each student ID is unique and follows a consistent format.
  const getCounterData = await CounterService.createOrFindCounterIntoDB(
    counterId,
    "student",
    session,
  );
  if (!getCounterData) {
    throw new AppError("Failed to generate counter data", 500);
  }
  return `${counterId}${getCounterData.sequenceValue.toString().padStart(4, "0")}`; // Generate the student ID by combining the counter ID with a sequence value that is padded with leading zeros to ensure a consistent length for all student IDs, this will help to create a unique and standardized format for student IDs in the database.
};

export const UserUtils = {
  generatedStudentId,
};
